### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by stuser81** [composewell/streamly#1062]
This is about https://github.com/composewell/streamly/issues/1061 and similar things.

Have you ever gotten frustrated by Haskell's unpredictable performance behavior? Has the thought crossed your mind, why am I even bothering with Haskell?

What are your main reasons for sticking with Haskell?

Would e.g. Rust not be more suitable for you, for these performance-critical programs?

(I use Haskell and by asking this, I'm mainly hoping for motivation to continue myself. Sometimes I have these second thoughts.)

**Comment by adithyaov** [comment]
> Have you ever gotten frustrated by Haskell's unpredictable performance behavior?

> Would e.g. Rust not be more suitable for you, for these performance-critical programs?

I don't know if this is specific to Haskell. Writing efficient code is not an easy task. Be it Rust, C, C++, or any other language performance-critical programs require good engineering with good knowledge of how the compiler works. 

That requires time, effort, and most importantly patience. The result might look very simple and easy to come up with that isn't the case in most scenarios.

GHC has its flaws, like any other compiler or optimizer but we have seen that it is very predictable and does a really good job. With things like compiler plugins, we can incorporate our own logic in the pipeline. There is no doubt that it's infinitely flexible.

But improving the compilation pipeline requires time and effort. It requires us to dig deep, figure out the problem and fix it accordingly. Specific solutions can be made using the compiler plugins and the general solutions can be pushed upstream.

GHC is not unpredictable. Given a major version, it predictably works, or predictably fails a specific condition. This predictability is essentially the best feature as we can deterministically figure out the problems and fix them.

Solving compiler issues is frustrating at times and deviates us from what we really want to do but solving the issues of the compiler works to the benefit of everybody. The folks who work on core GHC are very helpful and give really good suggestions and insights on the described problem.

> Has the thought crossed your mind, why am I even bothering with Haskell?

I'd be lying if I'd said never. This crossed my mind in the beginning when I did not care enough about what's happening under the hood. Now, I'm very confident that whatever the problem is there most definitely is a reasonable solution and with some effort, we can come up with one. This was the case with [fusion-plugin](https://hackage.haskell.org/package/fusion-plugin), which is a result of the motivation of a few enthusiastic developers.

Some developers clearly understand the compiler and are working on such issues. I'm hoping to gain such an understanding in the near future.

> What are your main reasons for sticking with Haskell?

There are a lot of reasons for this. But something that Haskell thrives on is its power of expressivity. The way you define and solve problems in a modular and expressive way is very important. The quality of code improves. Good quality code is easier to understand and eases the process of development. Contributions and reviews are easier. The community grows as a whole.

Personally, I think it's a beautiful language.

> I use Haskell and by asking this, I'm mainly hoping for motivation to continue myself. Sometimes I have these second thoughts.

Having second thoughts means that you really want to give this a shot and that's good. It's part of the process. Sometimes stuff might not make sense but rest assured there is always a sensible answer.

The community is very helpful and asking questions on Haskell forums, Reddit, and even opening issues on packages will lead you to some interesting solutions.

**Comment by stuser81** [comment]
@adithyaov Thank you for the motivating words.

Haskell itself is, in some ways, useless to me without streamly, so it's good to know you are committed to the project, at least for now. How are things looking wrt. long-term growth of the project (developers getting on board, usage in companies, etc.)? @harendra-kumar

**Comment by stuser81** [comment]
Thanks for the encouragement!
