### ISSUE TITLE
No instance for (MonadIO (ZipSerialM IO)) ?

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#111]
I'm trying to zipSerially 2 streams that require lifting some IO actions (liftIO), when I look at the [doc](http://hackage.haskell.org/package/streamly-0.5.1/docs/Streamly.html#t:ZipSerialM) I don't see any instance of MonadIO (ZipSerialM IO) and the compiler actually complains about it... can I do it ? am I missing something ?

**Comment by harendra-kumar** [comment]
`ZipSerialM` is not a `Monad`, it is just an `Applicative`. Therefore, it cannot have a MonadIO instance. However, that does not stop you from doing what you want to do, because streams can be easily interconverted. You can always use `liftIO` in a monadic stream and convert it into a Zip Applicative stream. For example:

```haskell
import Streamly
import qualified Streamly.Prelude as S
import Control.Monad.IO.Class

main = (S.toList . zipSerially $ (,,) <$> s1 <*> s2 <*> s3) >>= print
    where s1 = serially $ liftIO (putStrLn "hello") >> S.fromFoldable [1, 2]
          s2 = S.fromFoldable [3, 4]
          s3 = S.fromFoldable [5, 6]
```

`serially` converts a `SerialT` stream to a polymorphic stream and then `zipSerially` converts the polymorphic stream to a ZipSerial stream and zips it happily.

**Comment by harendra-kumar** [comment]
@nhenin I hope this solved your issue.
