### ISSUE TITLE
chunking combinators

### ISSUE THREAD

**Issue by naushadh** [composewell/streamly#116]
Absolutely love the native feeling APIs and the ease of adding concurrency to streams. I'd like to propose at-least 2 new additions to `Streamly.Prelude`.

- Ability to chunk a stream into a stream of lists, inspired from [conduit.slidingWindow](http://hackage.haskell.org/package/conduit-1.3.1/docs/Data-Conduit-Combinators.html#v:slidingWindow)
    ```haskell
    -- like so
    slidingWindow :: (Int, Monad m) -> SerialT m a -> SerialT m [a]
    -- or generally
    slidingWindow :: (Int, Monad m, IsSequence seq, Element seq ~ a) -> SerialT m a -> SerialT m seq
    ```

- Ability to flatten a stream of lists into stream of values, inspired from [conduit.concat](http://hackage.haskell.org/package/conduit-1.3.1/docs/Data-Conduit-Combinators.html#v:concat)
    ```haskell
    -- like so
    concat :: Monad m => SerialT m [a] -> SerialT m a
    -- or generally
    concat :: (Monad m, MonoFoldable mono) => SerialT m mono -> SerialT m (Element mono)
    ```

My use case is to parse a CSV file before chunking values into batches before asyncly issuing actions on each batch. `cassava`'s iterative parser yields multiple records per scan, and I believe I need the above two to flatten and re-chunk the stream.

Here's my first stab at trying to implement something like `slidingWindow`: https://github.com/naushadh/streamly/commit/8a7cec09145438a4e11a8c1bfe2a57f6fc712a22

Any advice would be appreciated.

**Comment by harendra-kumar** [comment]
@naushadh, yes these are useful combinators and missing from streamly. Thanks for your work and proposal on these. There are a couple of issues to be worked out before I can decide on the signatures of these. APIs that generate or flatten layers of stream like `concat` are pending and deliberately not implemented yet - see issue #10 . Ideally, I would like these to be streaming rather than using accumulated values in lists or some sort of non-streaming containers. 

I am not sure about using `MonoFoldable` for concat or having an API specifically to concat a stream of lists. In a more generalized world we would have a stream of streams, but for the sake of simplicity it might make sense to have a special API to flatten a stream of lists or maybe a stream of Foldables. Let me give this a thought and get back to you.

**Comment by naushadh** [comment]
Stream of streams would be nicer for sure; that way a user can feed in arbitrarily large sized chunk size and not have to worry about space all over again. Perhaps pairing it with `fromList/toList` and `fromFoldable/toFoldable` would cover all the cases.

I didn't know #10 already covered this; feel free to close this as a duplicate if you'd rather keep it all in one issue.

**Comment by harendra-kumar** [comment]
@naushadh the `chunksOf` operation that you implemented is a buffering/accumulating implementation. Since these operations are simpler to use compared to the streaming ones, I am considering implementing these as well. They can be exposed via the proposed `Streamly.Serial.Buffered` module as proposed in #130 . I guess it doesn't hurt if these ops are exposed via a separate module and the user explicitly knows what it means.

To start with you can prepare your `chunksOf` implementation and send a PR. Once we start, we can then add more on the same lines. The signature of chunksOf would be something like: 

```
chunksOf :: Monad m => Int -> Stream m a -> Stream m (Stream m a)
```

The inner streams would be buffered rather than streaming. In your implementation you can just use `fromList` before you yield the list to convert it into a `Stream`.

@pranaysashank is implementing `splitAt` in the same way. I guess one by one we can implement most of the ones mentioned in #10 . Buffering versions are easy to implement and easy to use as well and since there is still some thought and time to go into implementing the streaming ones it will be good to have something to work with until those are implemented.

**Comment by harendra-kumar** [comment]
Similarly a concat would be opposite:

```
concat :: Monad m => Stream m (Stream m a) -> Stream m a
```

**Comment by pranaysashank** [comment]
v0.7.0 now contains chunking / grouping / splitting operations. Take a look at the [Changelog](https://github.com/composewell/streamly/blob/v0.7.0/Changelog.md) and `Streamly.Prelude` for the relevant operators and their documentation.
