### ISSUE TITLE
Reexport Data.Function ((&)) from Streamly.Prelude

### ISSUE THREAD

**Issue by sullyj3** [composewell/streamly#1345]
Seems like this would be pretty handy! Is there any reason this would be a terrible idea?

**Comment by harendra-kumar** [comment]
We are not re-exporting anything in general just to keep things simple and avoid the debate of what to re-export and what not. 

But I think it may be a good idea to export this from Haskell Prelude itself as a counterpart of `$`, we can try asking the maintainers of `base` if they would be willing to do this. For streaming, dataflow programming this is very useful to write programs in such a way so that we have a forward flow of data.

**Comment by sullyj3** [comment]
Yeah, that would be even better.
