### ISSUE TITLE
Rolling window folds

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1372]
Figure out how to do rolling window folds, create one example.

**Comment by harendra-kumar** [comment]
A simple, incremental sliding window fold that does not require all the intermediate elements in a computation can be represented as follows:

```
rollWindow :: Int -> Fold m (a, Maybe a) b -> Fold m a b
```

This will maintain n elements in the window, when a new element comes it will slide out the oldest element and the new element and the old element are supplied to the argument fold. The `Maybe` is for the case when initially the window is filling and there is no old element.

Instead of a fixed window size as in the above API we may also have a window based on time e.g. keep 5 minutes data in the window (assuming a timestamped stream). For that we can provide:

```
-- rollTimeWindow timerTickSize timeWindowSize maxWindowSize
rollTimeWindow :: Double -> Double -> Int -> Fold m (a, Maybe a) b -> Fold m (AbsTime, a) b
```

The maxWindowSize is to limit the window to a maximum size in case the timeWindow contains too many items exceeding the memory of the system.

See also classifySessionsBy.

**Comment by harendra-kumar** [comment]
This is done in streamly-statistics package. See also #1442 .
