### ISSUE TITLE
`Streamly.Data.Fold.head` strangeness

### ISSUE THREAD

**Issue by shlok** [composewell/streamly#1404]
I’m using Streamly 0.8.1.1. The program

```haskell
import qualified Streamly.Data.Fold as F
import qualified Streamly.Internal.Data.Fold.Type as FTI
import qualified Streamly.Prelude as S

main :: IO ()
main = do
  let stream :: S.SerialT IO (Int, String) =
        S.fromList [(1, "a"), (2, "a"), (3, "b"), (4, "b"), (5, "c"), (6, "c")]
  let groupFold = F.toList
  result <- S.toList $ S.groupsBy (\x y -> snd x == snd y) groupFold stream
  print result
```

gives an entirely expected result (showing that our grouping works exactly as expected):

```
[[(1,"a"),(2,"a")],[(3,"b"),(4,"b")],[(5,"c"),(6,"c")]]
```

Changing `groupFold` to `F.last`, we again get an entirely expected result:

```
[Just (2,"a"),Just (4,"b"),Just (6,"c")]
```

However, changing `groupFold` to **`F.head`**, we get an **unexpected result**:

```
[Just (1,"a"),Just (2,"a"),Just (3,"b"),Just (4,"b"),Just (5,"c"),Just (6,"c")]
```

Interestingly, by changing `groupFold` to `FTI.foldl1' (\x _ -> x)` (a some sort of a reimplementation of `F.head`), we now get the expected result:

```
[Just (1,"a"),Just (3,"b"),Just (5,"c")]
```

What are your thoughts on this? (I suspect that this may be related to some of the known issues listed [here](https://github.com/composewell/streamly/issues/455).)

**Comment by harendra-kumar** [comment]
It looks non-intuitive but it is the correct behavior by design. One may argue for alternative semantics though.

The reason is - if the collecting fold terminates, it terminates the current group and the next group starts from where the previous fold/group terminated. So F.head would always terminate on the first element of the group and we will start the next group from the remaining stream. Therefore, grouping with F.head would behave like `id`.

Your new implementation of head is a non-terminating fold, it returns the head and discards the rest of the group. You could also use `F.splitWith F.head F.drain` for the same behavior.

BTW, earlier streamly folds were all non-terminating, but it changed in 0.8.0.

Perhaps we can elaborate this in some documentation to avoid the pitfall.

**Comment by harendra-kumar** [comment]
BTW @shlok you may find https://github.com/composewell/streamly-statistics interesting. We are also building a technical analysis indicators library on top of that, but that is closed as of now, we may decide to open it though.

**Comment by shlok** [comment]
@harendra-kumar Thanks for the swift response! This behavior of the grouping functions was unexpected to me, but it makes sense if one thinks about it. (I agree that documenting this would be useful at some point, but I’m not aware which functions other than the grouping functions could lead to similar misunderstanding.)

> BTW @shlok you may find https://github.com/composewell/streamly-statistics interesting. We are also building a technical analysis indicators library on top of that, but that is closed as of now, we may decide to open it though.

Thanks! I will keep an eye on this interesting library in the future.
