### ISSUE TITLE
Example request: File to ByteString lines

### ISSUE THREAD

**Issue by flip111** [composewell/streamly#164]
I only found this function https://hackage.haskell.org/package/streamly-0.6.0/docs/Streamly-Prelude.html#g:7 on reading IO to String. If it's possible i would like to request an example for the following:

* Reading lines of text from a file. Not loading the whole file in memory.
* Process file line by line (for example count characters per line and give average of characters per line at end of the program)
* Only character decoding for line endings 0x0A & 0x0D (Linux style & Windows style)
* No further decoding of characters. One character is just any Word8
* Read into ByteString or any other data structure that uses pinned memory. https://ghc.haskell.org/trac/ghc/wiki/Commentary/Rts/Storage/GC/Pinned

I like this example to find out if streamly can be used with high speed (file) IO and also high speed FFI where additional copying/allocating is not needed.

Second example to reading to `Data.Text` would also be appreciated. But not as important as first example.

I'm very confused why i could only find this IO function that read into `String` type ..

**Comment by harendra-kumar** [comment]
> I'm very confused why i could only find this IO function that read into String type ..

That's a valid confusion. We have also mentioned in the [cabal description](https://hackage.haskell.org/package/streamly) that there are no IO APIs yet. We have been busy in trying to get several fundamentals right so that we do not have to change things later. Moreover, nobody explicitly asked for these yet. Most of the pieces are in place now, we can provide the APIs you are looking for.  I will update you soon on that.

**Comment by flip111** [comment]
@harendra-kumar Thanks so much. Really looking forward to it. By the way .. network IO with HTTP would also be interesting.

**Comment by harendra-kumar** [comment]
@flip111 just hang on. I have the file IO code working, just need to finish it and commit.

**Comment by harendra-kumar** [comment]
@flip111 I have been working on the IO stuff, there has been quite a bit of progress but nothing committed to master yet. The temporary code is on https://github.com/composewell/streamly/tree/io2 branch, in case you want to have a look, but this is completely in flux. There have been major additions as part of this change e.g. polymorphic arrays of storables (using pinned memory), composable folds, sinks, grouping and buffering code. I guess it will take a couple more weeks to get it into master, and then some more time to release it. Performance is turning out to be pretty good, it is equivalent to bytestring IO in many cases and even better in others.

**Comment by flip111** [comment]
Hi, i've read the comments in the commits. I saw that there were some open considerations. Unfortunately i can't provide input/feedback on these parts because of the lack of knowledge. One thing that stood out was the presents of `Streamly.String`. Which seemed a bit odd to me, String being a bit crippled data type for text. Perhaps Streamly.Text would be more appealing to most people. Well i guess it can't hurt either to have a Streamly.String there for the people who want it.

**Comment by flip111** [comment]
It's also that String has no Unicode support. Can you give an example
scenario of when streaming char by char is useful?

**Comment by harendra-kumar** [comment]
Well, `Text` is nothing but `unstream . transform . stream`. We can apply all those transformations to streams of Chars i.e. without having to use stream/unstream, because we already have a stream. Most of the combinators that are available in the `Text` package are just general stream combinators, you won't need anything special. The only cases where unicode aware treatment is required is case conversion and we will provide special combinators for those cases that only apply to streams of chars and not polymorphic streams of `a`. Those will be part of the `Streamly.String` module. `String` in fact means unicode strings.

**Comment by wismill** [comment]
> The only cases where unicode aware treatment is required is *case conversion*

Do you mean [normal forms](https://en.m.wikipedia.org/wiki/Unicode_equivalence)? Yes this is pretty important.

**Comment by harendra-kumar** [comment]
@wismill I meant, case-conversion i.e. converting from lower case to upper case or vice-versa. Converting case may increase or decrease the length of the string. So it is not a simple `map` operation and has to be handled specially, it would rather be a `concatMap` operation. So we can either use the stock `concatMap` in Streamly or provide special combinators for case conversion.

Normalization, as you referred by `normal forms`, is not handled natively by the `text` package. The text package does not keep text in a normalized form, programmer needs to do that explicitly using the `normalize` function from `text-icu` or from the `unicode-transforms` package. Incidentally, I am the author of https://github.com/composewell/unicode-transforms as well which performs unicode normalization.

**Comment by wismill** [comment]
@harendra-kumar I was not aware of this issue with case conversion. I will definitely look at your other package and continue discussion there.

**Comment by harendra-kumar** [comment]
@flip111 fileIO has finally been merged on the master branch. See the README and haddock docs for usage. You can see your example in the README file. Here is the `+RTS -s` output running line length histogram on a 500 MB project gutenberg file:

```
cutlass:/vol/hosts/cueball/workspace/packages/streamly/examples  (master)$ du -sm src.txt 
549	src.txt
cutlass:/vol/hosts/cueball/workspace/packages/streamly/examples  (master)$ time ./utils src.txt +RTS -s
fromList [(0,2107802),(1,399842),(2,422854),(3,449329),(4,526113),(5,353624),(6,3042747),(7,3936415),(8,351),(9,3143)]
   8,254,874,912 bytes allocated in the heap
       4,838,384 bytes copied during GC
          62,088 bytes maximum residency (2 sample(s))
          40,312 bytes maximum slop
               0 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0      7362 colls,     0 par    0.019s   0.022s     0.0000s    0.0000s
  Gen  1         2 colls,     0 par    0.000s   0.000s     0.0001s    0.0002s

  INIT    time    0.000s  (  0.002s elapsed)
  MUT     time    3.005s  (  3.157s elapsed)
  GC      time    0.019s  (  0.023s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time    3.025s  (  3.183s elapsed)

  %GC     time       0.0%  (0.0% elapsed)

  Alloc rate    2,746,747,662 bytes per MUT second

  Productivity  99.4% of total user, 99.2% of total elapsed


real	0m3.188s
user	0m3.026s
sys	0m0.157s
```

Feedback on performance or API is very welcome.

I have not implemented functions to convert to bytestrings, that is not required for using the library. It may be required only for interoperability. Socket IO will be coming soon.

**Comment by harendra-kumar** [comment]
@flip111 Socket/Client/Server modules are now available on the master branch. Take a look at the examples directory for networking examples:

* https://github.com/composewell/streamly/blob/master/examples/EchoServer.hs
* https://github.com/composewell/streamly/blob/master/examples/FromFileClient.hs
* https://github.com/composewell/streamly/blob/master/examples/FileSinkServer.hs

Let me know if you have any feedback on this or need anything more, or if we can close this issue.

**Comment by harendra-kumar** [comment]
> Quite a lot of haskell learning material says we should avoid String like the plague if we want performance.

I think this is a heavy hammer recommendation given to avoid the pitfalls that you can get into when using String. Because sometimes (or quite often) you may run into problems so just avoid it altogether.

If you are processing data without storing it (i.e. streaming) then String/List do not pose any problems, they are efficient due to foldr/build fusion. But if you are using them to store data in memory at a large scale then it could be bad. One, they would take many times the storage actually required to store those chars. Two, this memory will have to be allocated, copied by the GC.

Also, a number of operations on lists that are in Prelude/base could be problematic because of accumulating lists in memory. So you never know when you might inadvertently be accumulating lists in memory, leading to painful debugging. This kind of problem won't exist when you use stream of char rather than strings, because the stream APIs ensure that data is not accumulated, it is processed in a truly streaming fashion.
