### ISSUE TITLE
aheadly unfolded stream elements written out of order

### ISSUE THREAD

**Issue by MuratOzsoyler** [composewell/streamly#170]
I wrote my first trial with streamly. As far as I remember from the tutorials and references, aheadly, although works asyncronously, returns result in the generation order. But following program prints out of order values on my computer.

```haskell
main :: IO ()
main = 
    -- putStrLn "---- serially ----"
    -- >> (runStream $ serially $ SP.mapM print $ generate 10)
    {- >> -} {- putStrLn "---- aheadly ----"
    >> -} (runStream $ aheadly $ SP.mapM print $ generate 10)
    -- >> putStrLn "---- asyncly ----"
    -- >> (runStream $ asyncly $ SP.mapM print $ generate 10)

generate :: (Monad m, IsStream t, Ord b, Num b) => b -> t m b
generate lim = SP.unfoldr go 0
  where
    go n = do
        if n >= lim 
          then Nothing
          else Just (n, n + 1)
```

If I uncomment the commented lines or even uncomment previous `putStrLn` everything is OK (even asyncly writes values in order!).

Is there any point I have missed?

Thanks in advance

**Comment by pranaysashank** [comment]
`aheadly` can run actions concurrently, but presents the results in serial order. In your example, the printing can happen concurrently, so you'd be seeing them out of order sometimes. The results which are `()` (after mapping over the stream) are collected serially.  
You can try running the following to see it:

```Haskell
main :: IO ()
main = do
      putStrLn "---- aheadly ----"
      xs <- (toList $ aheadly $ SP.mapM (\x -> print x >> return x) $ generate 10)
      print xs
```

>  (even asyncly writes values in order!).

It might seem so because `generate` is a simple pure function that returns values immediately. Try introducing a threadDelay before printing to see a difference.

Take a look at this [example](https://hackage.haskell.org/package/streamly-0.6.0/docs/Streamly-Tutorial.html#g:24) in the tutorial which demonstrates this.

**Comment by MuratOzsoyler** [comment]
Hi Pranay,

Thank you for your prompt answer.

Thus we can say that, any action on right side of the aheadly is not
guaranteed to be in order, on left side, they are in order, right?

Regards,

Murat Özsöyler


Pranay Sashank <notifications@github.com>, 23 Oca 2019 Çar, 21:05 tarihinde
şunu yazdı:

**Comment by pranaysashank** [comment]
>any action on right side of the aheadly is not guaranteed to be in order

`aheadly`, based on the demand from the consumer, can speculatively run the actions concurrently.

> on left side, they are in order, right?

Yes, I guess we can say that. In above examples `runStream` and `toList` always get the results in serial order.

**Comment by MuratOzsoyler** [comment]
Thank you for your kind help.

**Comment by harendra-kumar** [comment]
@MuratOzsoyler A good way to put it can be that `aheadly` always guarantees presenting the results/output values in order but side effects (e.g. print is a side effect) can happen out of order because of the concurrency.
