### ISSUE TITLE
Integrate streamly IO with stdio

### ISSUE THREAD

**Issue by FongHou** [composewell/streamly#175]
Hi, have you considered using stdio https://haskell-stdio.github.io/stdio/ as streamly IO backend?

It seems that both projects have been designed from ground-up with high performance in mind, also take a fresh view on the design and implementation that are not tied to existing Data.ByteString/Data.Text ecosystem (e.g. as conduit ecosystems are). It'll be awesome to see these two projects can be integrated and perform well together. 

PS. I don't mean to judge stdio (vs. bytestring/text) nor ask anything specific as the design and implementation of these are well beyond my current knowledge. Just want to say I'm excited to see what these two expressive pieces of engineering can accomplish together.

Thanks!

**Comment by harendra-kumar** [comment]
@FongHou thanks for the suggestion. I did look at the stdio as it was announced and I appreciate the efforts to create a high performance IO library. In fact some of the stuff in there is similar to my own thinking.

But unfortunately, I do not see if these two can be directly integrated by making one depend on the other. Streamly's IO routines and APIs (not yet committed) are designed to work in streaming fashion and they are designed to utilize stream-fusion with the rest of the stream code for as best performance as we can get. Especially because of streaming nature the APIs may be quite different and I think it is better to let them evolve independently. Though, I will try keeping an eye on the stdio library if there is any code or ideas that can be picked up and reused.

**Comment by FongHou** [comment]
Hi @harendra-kumar, I'm glad to hear your thoughts on that. Streamly is a great achievement in itself in terms of performance. I'm looking forward to seeing what's coming. Will 0.7 include IO APIs for ByteString/Text types?

**Comment by harendra-kumar** [comment]
Thanks @FongHou for the kind words. An extraordinary amount of effort has gone into it to unify diverse functionality into a simple API with high performance. Yes, 0.7 should have the IO APIs. ByteString and Text types won't be needed as we can do all that they do with native streams of Chars with equivalent or better performance.
