### ISSUE TITLE
Rate limiting - missing constraint ?

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#179]
Code below compiles, but rate is not taken into account:
```hs
main = runStream $ S.mapM putStrLn $ asyncly $ avgRate 1 $ S.repeat "Ping!!!"
```
It works only with `S.repeatM $ pure "Ping!!!"`

Looking at `avgRate` (and all the rate limiting functions) signature(s):
```hs
avgRate :: IsStream t => Double -> t m a -> t m a
````
shouldn't there be additional constraint (MonadIO)?
Figuring out what's wrong in cases like this with non-trivial stream composition might be very time consuming.

**Comment by harendra-kumar** [comment]
@mryndzionek `avgRate` and other rate related combinators work only for concurrent combinators. `repeat` is not a concurrent combinator whereas `repeatM` is concurrent that's why it works only for `repeatM` - which combinator is concurrent and which is not is documented under each combinator. This behavior of rate combinators has been documented in the docs under the `Concurrency Control` section:

> These control parameters have no effect on non-concurrent combinators in the stream, or on non-concurrent streams`.

I agree that someone who has not read the docs carefully may have to spend some time to discover this. The easiest short term fix could be to have an emphasized warning under the documentation of `avgRate` and other rate combinators indicating that this does not work for serial combinators.

In the long term, we can perhaps do better. We can either make the rate combinators effective for serial combinators as well or we can have a diagnostic flag to emit a warning in the cases where the setting may not work and has been used. But both of these options will require some work to be done.

**Comment by mryndzionek** [comment]
Okay, thanks for quick reply. So it's just that it isn't so easy to have this verified statically? If you have some ideas how to accomplish this I'm willing to investigate. Cheers!
