### ISSUE TITLE
Consistency of argument order

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2052]
- Handle.getChunk
- Handle.putChunk
- Array.getIndex
- Array.putIndex
- Filesystem.getChunk
- Filesystem.putChunk

**Comment by harendra-kumar** [comment]
Operations in `base` have Handle as the first argument. But in streamly all APIs use the object that we are operating on as the last argument, this is useful when we are transforming the object in a pipeline. Though this may not be useful for Handle because we it is not transformed. However, all APIs in the FileSystem.Handle module use Handle as the last argument, so we can make the odd ones also consistent with that, currently only putChunk is different.

**Comment by harendra-kumar** [comment]
However, if I look at Streamly.Internal.FileSystem.File most operations have FilePath as the first argument. So maybe we can make everything like that?

**Comment by harendra-kumar** [comment]
```
getIndex :: Int -> Array a -> m a
putIndex :: Int -> a -> Array a -> m ()

-- Handle
getChunk :: Int -> Handle -> m (Array Word8)
putChunk :: Handle -> Array a -> m ()

-- Socket
getChunk :: Int -> Socket -> IO (Array Word8)
putChunk :: Socket -> Array a -> IO ()

-- File
putChunk :: FilePath -> Array a -> IO ()
```

All get seem to be consistent. All puts are consistent except `putIndex`. gets specify the location, most specific component first, and puts specify the location, most specific component first, and then what to put.

We can change putIndex to make it consistent with putChunk etc:

```
putIndex :: Int -> Array a -> a -> m ()
```

Then we can also change the peek/poke in Unbox to:

```
peekByteIndex :: Int -> MutableByteArray a -> IO a
pokeByteIndex :: Int -> MutableByteArray a -> a -> IO ()
```

**Comment by harendra-kumar** [comment]
Changed putIndex/modifyIndex for arrays.
