### ISSUE TITLE
C, Haskell/streamly, Rust

### ISSUE THREAD

**Issue by stuser81** [composewell/streamly#2226]
Some of you came originally from C if I recall correctly. Because C was not working for you, you developed streamly for Haskell.

* What was wrong with C? Unmaintainable mess?
* Would you have come to the same conclusion if you had started with Rust?

**Comment by harendra-kumar** [comment]
Unbridled mutability, and lack of modularity enforcement  is what is wrong with C. A large programs tends to become a big ball of mud unless there is a very good discipline maintained which is possible but very hard practically. The ability to change state from anywhere makes it hard to understand large programs. You are always thinking does this structure change who all can change it, and it could be practically anywhere in a large program, so you are not sure unless you understand the entire mess, and this leads to things breaking even if you make a very small and seemingly harmless change in the program.

I have not programed with Rust but I guess it would be much less so in Rust because you more powerful tools to attack these problems. But I guess the purity in Haskell allows more possibilities for better composability.
