### ISSUE TITLE
question: merging into a running stream

### ISSUE THREAD

**Issue by mattsawyer77** [composewell/streamly#252]
Hello, and thanks for this super cool library. I'm definitely not a Haskell expert but I am currently using Streamly with great success. My project is currently doing `foldWith async` on a list of streams and then (after several stream processing functions) running it with runStream. But I'd like to have another thread that would merge additional streams to this list somehow after runStream is executed. Any suggestions?

**Comment by harendra-kumar** [comment]
Try`concatMapBy async` from the master branch. Let us know if that does not solve your problem.

**Comment by harendra-kumar** [comment]
Take a look at this example for a sample use of `concatMapBy` https://github.com/composewell/streamly/blob/master/examples/FileSinkServer.hs .

**Comment by mattsawyer77** [comment]
Thanks for the quick response, @harendra-kumar. Though I'm not sure this (alone, anyway) would solve my problem, though I may be lacking understanding. 

Maybe I should explain what I'm trying to do further. My app dynamically builds up a list of streams, where each of these streams is a (potentially) infinitely running child process (each process's output is streamed line-by-line). Then I fold those streams with async as mentioned above and do some more pipeline processing on the merged stream, then call runStream (now known as drain, it seems?). After some time elapses, I want to poll again via some other thread which could result in more individual processes I'd like to fold into the already running stream. I don't want to have to kill the already running child processes to build a totally new list of streams to merge.

**Comment by harendra-kumar** [comment]
This is exactly what `concatMapBy` is for. Using `foldWith` you fold a static container of streams. Using `concatMapBy` you fold a dynamic stream instead. Here is the signature of `concatMapBy`:

```
concatMapBy :: IsStream t => (forall c. t m c -> t m c -> t m c) -> (a -> t m b) -> t m a -> t m b
```

To understand it in relation with what you already know, we can implement `foldWith` using `concatMapBy`:
```
{-# LANGUAGE RankNTypes #-}
import Streamly hiding (foldWith)
import qualified Streamly.Prelude as S

foldWith :: (IsStream t, Foldable f) => (forall a. t m a -> t m a -> t m a) -> f (t m a) -> t m a
foldWith f xs = S.concatMapBy f id (S.fromFoldable xs)
```

For example, if you want to read a list of files from standard input and merge all the contents of those files asynchronously in a single stream you can use something like: `concatMapBy async (\filename -> readFileAsAStream fileName) readFileNamesFromStdin`. Since stdin is a continuous stream, as soon as you enter another name on stdin that file will get added to the merged stream.

Hope this helps. Let us know if you need more clarifications. BTW, in case your team needs professional support on how to use streamly effectively in your solutions you can contact us at support@composewell.com.

**Comment by pranaysashank** [comment]
`concatMapBy` is now released as `concatMapWith` in the library.

**Comment by harendra-kumar** [comment]
I assume this question is answered. @mattsawyer77 please reopen if you have any more questions regarding this.
