### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shinzui** [composewell/streamly#2737]
Is there an updated roadmap for Streamly? We're using it heavily on a project and needed to reach `Internal` modules. It would be nice to know that there is a plan to stabilize the API.

**Comment by harendra-kumar** [comment]
Please let us know which internal APIs you are using so that we can prioritize it. We do not have a very well defined roadmap doc but we are continuously working on stabilizing and releasing the experimental APIs. Development has slowed down in the past few months due to lack of resources but we intend to continue working on it and get 0.11 out in a few months.

**Comment by shinzui** [comment]
Thank your response and for providing such a great library. 

> Please let us know which internal APIs you are using so that we can prioritize it. 

From `Data.Internal.Data.Stream`:

- `catMaybes`
- `catEithers`
- `unionBy`

From `Data.Internal.Data.Fold`:

- `foldtM'`
- `foldlM1'`
