### ISSUE TITLE
Build fails with latest stack nightly on MacOS

### ISSUE THREAD

**Issue by AliceRixte** [composewell/streamly#2844]
See the output of this [CI](https://github.com/composewell/streamly/actions/runs/11062893476/job/30738127480?pr=2842) in this PR #2842 for more details.

This replaces the issue #2833.

**Comment by harendra-kumar** [comment]
@AliceRixte did you open an issue in the stack repo about this? They need to see this.

**Comment by mpilgrem** [comment]
@harendra-kumar, as also posted in the linked Stack issue, I believe this is caused by `streamly.cabal` including a `*.m` file in `c-sources`. With GHC 9.8.2/`Cabal-3.10.2.0`, Cabal enforces that `c-sources` is only for `*.c` files. I have asked in the 'Cabal and Hackage' room on Matrix where Objective-C source files are intended to be specified in Cabal files.

**Comment by AliceRixte** [comment]
@harendra-kumar Thank you for dealing with this issue. Do you have any idea when you will make this available on Stackage ? It would be great if you noticed me here when you do.

Cheers !

**Comment by harendra-kumar** [comment]
@AliceRixte the fix will go in streamly 0.11 release but that will take some more time.

If you don't want to wait till 0.11 you can help us with https://github.com/composewell/streamly/issues/2868 .

**Comment by AliceRixte** [comment]
It's fine I can wait for 0.11, I'll use cabal meanwhile. Thank you for your answer and your help !
