### ISSUE TITLE
unfoldrM without MonadAsync constraint

### ISSUE THREAD

**Issue by chfin** [composewell/streamly#326]
I'm trying to generate a stream by unfolding with a monadic step function. The monad can be anything including non-IO monads such as `State`, `Reader`, or `Identity`. However, since `unfoldrM` has a `MonadAsync` constraint, I'm basically forced to do everything in IO. Would it be possible (and make sense) to have an unconstrained version of `unfoldrM`?

I guess the constraint comes from `unfoldrM` being concurrent by default, is that right? Is there a reason for not having a non-concurrent version?

**Comment by FongHou** [comment]
Sounds like you should use pure versions of unfold instead because State/Reader monads (and transformers stack) are dischargeable "pure" monads that are just syntactic sugar for "threading extra inputs and outputs through pure functions implicitly". You can also thread them explicitly through unfold's step function and seed parameter. If you already had some "monadic but pure" step function using 'State s' or 'Reader r', you have to do some extra unwrap/rewrap dancing around runStateT/StateT, runReaderT/ReaderT to get 's' and 'r' in or pull them out of the unfold seed parameter.

unfoldr :: (Monad m, IsStream t) => (b -> Maybe (a, b)) -> b -> t m a

or 

unfold :: (IsStream t, Monad m) => Unfold m a b -> a -> t m b

Do you have a specific example use case?

**Comment by FongHou** [comment]
btw, it's much hard after you already have a 't m b', but want to lift m to 'StateT m' or "ReaderT m', streamly 0.7.0 have [liftInner etc](https://github.com/composewell/streamly/blob/9fca294e1ce52c251d4ec854cd8541d2e235f090/src/Streamly/Internal/Prelude.hs#L391)

**Comment by harendra-kumar** [comment]
> I guess the constraint comes from unfoldrM being concurrent by default, is that right? Is there a reason for not having a non-concurrent version?

Yes, the constraint comes because of the overloading of `unfoldrM` to concurrent version for non-serial streams. We are contemplating having monomorphic versions of combinators specialized to a specific stream type instead of using polymorphic combinators. Then you will have unconstrained unfoldrM for serial streams.

For now you can try what @FongHou suggested. You can always lift the inner monad to StateT or ReaderT using lifting combinators in "Streamly.Internal.Prelude" (these will be released soon). I guess you can also use `unfoldrM` in IO monad and then `hoist` (Streamly.Internal.Prelude.hoist) the monad to Identity using unsafePerformIO, if your logic is pure then unsafePerformIO should be safe.

Currently some modules (e.g. `Streamly.Streams.StreamD`) are unexposed, we will expose them soon via Internal module tree. Otherwise, I could have suggested making an unconstrained version of `unfoldrM` like this:

```
unfoldrMSerial :: Monad m => (b -> m (Maybe (a, b))) -> b -> SerialT m a
unfoldrMSerial step seed = StreamD.fromStreamD (StreamD.unfoldrM step seed)
```

**Comment by chfin** [comment]
Thanks for your comments.

My use case is an algorithm that generates skip grams (with an arbitrary cost function). For sampling, I  flip a coin for every generated skipgram to decide whether to include it in the output or not. The coin is supplied as a monadic action of type `m Bool`. `m` might be `IO` for a random coin, `State` for a pseudo-random coin, `Identity` with `pure True` for a non-sampling variant, or whatever else you might come up with. I would like to avoid having to decide between `IO` and non-`IO` beforehand.

**Comment by harendra-kumar** [comment]
@chfin the internal stream modules have now been exposed on the master branch. I have opened a PR that introduces an `unfoldrM` without `MonadAsync` constraint. Once this is merged you can use streamly from the master branch and import `Streamly.Internal.Data.Stream.Serial` to use the unconstrained combinator. Currently this is `Internal`, but this can be exposed officially in future releases.

**Comment by chfin** [comment]
Awesome! Thanks a lot!

**Comment by pranaysashank** [comment]
Reopening this function as the function is not exported from a non-Internal module.

**Comment by harendra-kumar** [comment]
Master branch now has a Streamly.Data.Stream module supporting all combinators without MonadAsync constraint.
