### ISSUE TITLE
How to use FileSystem API

### ISSUE THREAD

**Issue by hasufell** [composewell/streamly#356]
streamly 0.7.0 has the module [Streamly.FileSystem.Handle](https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-FileSystem-Handle.html) exposed.

Looking at that module there is:

```hs
read :: MonadIO m => Unfold m Handle Word8
```

but not documentation on how to construct an Unfold and how to consume it.

When I click on [Unfold](https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Data-Unfold.html#t:Unfold) I get to an empty data declaration and lengthy performance discussion, but no description of how to use it either.

Clicking on the link provided in Streamly.Data.Unfold documentation about combinators I get [Page not found](https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Internal-Data-Unfold.html).

If this API is not yet usable, then it shouldn't be exposed. And if it's usable it should be documented properly, with examples.

**Comment by pranaysashank** [comment]
At the top of the `Unfold` module haddock page it's mentioned,
>  An Unfold can be converted into a stream type using `S.unfold` by supplying the seed.

However it's not properly linked to the [unfold](https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Prelude.html#v:unfold) combinator from Streamly.Prelude.

Thanks for bringing this to notice, we'll try to get these documentation fixes in the next minor release

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Array.html also points nowhere in https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Prelude.html#v:toList

I would also expect some basic usage examples of the filesystem API.

**Comment by pranaysashank** [comment]
Did you check the examples directory?

**Comment by hasufell** [comment]
> Did you check the examples directory?

No, I don't see it linked in the documentation

**Comment by harendra-kumar** [comment]
@hasufell thanks for raising the issue, we need that for improving the docs. 

Some points regarding the documentation of 0.7.0:

* 0.7.0 has introduced several features/modules and we are lagging behind on documentation for that
* We are aware of the broken links, when uploading we were not sure how hackage would build the documentation. We will address this issue in the upcoming minor release. For now you can build the haddocks yourself to fix this issue, as the [streamly hackage landing page](http://hackage.haskell.org/package/streamly) mentions:

```
$ cabal haddock --haddock-option="--show-all"
$ stack haddock --haddock-arguments "--show-all" --no-haddock-deps
```
* We need to put a tutorial section for filesystem/network API usage, we are working on that.
* The [landing page of streamly on hackage](http://hackage.haskell.org/package/streamly) mentions the examples link. The Tutorial module also mentions the examples directory at several places. However, some links to the example files in the tutorial are also broken. We need to fix that.
* Some examples are using APIs from Internal modules because, (1) the APIs may not have got enough soak time to be exposed for long term support, (2) some internal APIs used in the examples may have better performance because we have not yet released the GHC plugin for bringing the more idiomatic exposed APIs at par.

Let's keep this issue open until we address everything mentioned here.

**Comment by harendra-kumar** [comment]
* You may also find these slides useful: https://www.slideshare.net/HarendraKumar10/streamly-concurrent-data-flow-programming . They have many usage examples. These slides were used in a functional conference talk on streamly available on youtube: https://www.youtube.com/watch?v=uzsqgdMMgtk .

* There is a streamly-examples package available here: https://github.com/composewell/streamly-examples . This contains all the examples from the above presentation and will have more examples in future.

The tutorial module in the package is correct but incomplete, it needs an overhaul to accommodate the new changes to the library.

**Comment by hasufell** [comment]
Thanks a lot @harendra-kumar !

I managed to replace my manual file-copy loop with streamly: https://github.com/hasufell/hpath/commit/200fc9b58114da0d470c8c1a3d41082a692978cb

One thing I noticed there is that it doesn't work on file-descriptors. My library doesn't use handles anywhere, since I find them problematic and prefer to use the low-level unix package. Would there be a chance to have filesystem based API that is platform specific or is that out of scope?

**Comment by pranaysashank** [comment]
Did you check the FD* modules [here](https://github.com/composewell/streamly/tree/master/src/Streamly/FileSystem), they are not exposed currently but they _might_ be exposed in the future.

Let us know if you find them useful.

**Comment by harendra-kumar** [comment]
> The examples has no explanation why this implementation was chosen over something naive like S.fold (FH.write dest) (S.unfold FH.read source)

`S.fold (FH.write dest) (S.unfold FH.read source)` would read the file using the `defaultChunkSize` of 32K from the system, it gets a stream of chunks of 32K size from when reading from system, `FH.read` flattens those chunks into a byte stream. `FH.write` converts the bytes into 32K chunks again for writing to the system.

On the other hand `toChunksWithBufferOf` directly gives us a stream of chunks themselves and that too chunks of specified size, for copy a larger chunks size performs better (in the example we used 256K). `writeChunks` then writes those chunks directly. Thus it avoids unnecessary conversion to a byte stream and is therefore faster.

Instead of `toChunksWithBufferOf` you can use `readChunksWithBufferOf` which is officially exposed via `Streamly.FileSystem.Handle` module. We will update the example, and will also try to put some comments regarding the choice of APIs.

**Comment by harendra-kumar** [comment]
@hasufell instead of opening the file yourself and creating filehandles you can use the routines from `Streamly.Internal.Filesystem.File` to work directly on file paths, like the version of cp in this https://github.com/composewell/streamly/blob/master/examples/FileIOExamples.hs :

```
cp :: FilePath -> FilePath -> IO ()
cp src dst =
      File.fromChunks dst
    $ File.toChunksWithBufferOf (256*1024) src
```

**Comment by hasufell** [comment]
@harendra-kumar I can't use that API, since [my library](https://hackage.haskell.org/package/hpath-0.9.2/docs/HPath.html) uses ByteString for filepaths, which is the only correct representation, because [String is problematic](https://gitlab.haskell.org/ghc/ghc/wikis/proposal/abstract-file-path).
Thus, I avoid converting to and from FilePath.

**Comment by harendra-kumar** [comment]
We have not exposed that module yet because FilePath is not the representation we want for paths.

**Comment by hasufell** [comment]
Another link that points nowhere at: https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Data-Fold.html#v:toList to https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Array.html

**Comment by adithyaov** [comment]
Master documentation:   https://composewell.github.io/streamly/master/index.html

**Comment by harendra-kumar** [comment]
Unfold module is properly documented now.
