### ISSUE TITLE
Responding to decodeUtf8 failing to decode

### ISSUE THREAD

**Issue by kozross** [composewell/streamly#392]
It's completely possible that when I call [``decodeUtf8``][1] on a stream, it might not contain valid UTF-8. I'd like to be able to respond to that in my code, but I'm not sure how this can be done. Given the generality of ``decodeUtf8``, it wouldn't be hard for me to provide it with ``MonadError`` capabilities, but how can I detect that the decode failed?

[1]: https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Data-Unicode-Stream.html#v:decodeUtf8

**Comment by harendra-kumar** [comment]
You can decode with error handling using `decodeUtf8Either` available [here](https://composewell.github.io/streamly/Streamly-Internal-Data-Unicode-Stream.html) in `Streamly.Internal.Data.Unicode.Stream`. You can also resume decoding an incomplete stream after encountering an error using `resumeDecodeUtf8Either`. You can see these APIs in action [in this example](https://github.com/composewell/streamly/blob/master/examples/WordCount.hs).

**Comment by kozross** [comment]
That first link 404s for me.

**Comment by harendra-kumar** [comment]
updated.

**Comment by kozross** [comment]
@harendra-kumar Thanks! I guess that site hosts the most up-to-date documentation for Streamly?

**Comment by harendra-kumar** [comment]
Yes, you can find the master branch documentation at https://composewell.github.io/streamly/master/Streamly-Internal-Data-Unicode-Stream.html .  It is currently updated manually, but we will try to automate it.

This is in flux currently but hopefully it will stabilize soon and we will also have an index page so that you can easily navigate the documentation by releases.
