### ISSUE TITLE
Stateful stream concurrency question

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#436]
I would like to use something like the AcidRain example, so a stateful stream, but with a 'bigger' state. By bigger I mean something like a 2D vector of cells/structs. Will the contention be on the whole vector, or the individual cells. Is it possible to have fine-grained concurrency on individual cells, or would I be better off with something like STM?

**Comment by harendra-kumar** [comment]
Note that AcidRain example modifies state inside a serial stream/single thread and not inside concurrent threads, therefore there is no contention. If you want to use it the same way then you don't have any issue whatever size of the state you may have.

However, if you want to modify shared state from concurrent tasks - https://github.com/composewell/streamly/blob/master/docs/transformers.md contains a brief note about shared state in concurrent applications. Currently in concurrent applications, modifications to StateT would not be carried to the parent computation that forked the tasks, #247 targets to solve this problem.

If you want to share state across concurrent tasks, you can use an IORef or some other mutable structure (e.g. a mutable vector) shared via ReaderT or StateT. 

If you can partition the shared state such that different threads are modifying different cells at the same time then you could use a boxed array of IORefs (http://hackage.haskell.org/package/streamly-0.7.1/docs/Streamly-Internal-Data-Array.html) and different threads can modify different cells (IORef in the array) concurrently. You can still use atomicModifyIORef to modify the IORefs so that even if multiple threads are modifying the same IORef concurrently it should still work correctly, but contention will be reduced because you have partitioned the state across many cells.

**Comment by mryndzionek** [comment]
Thank you!
