### ISSUE TITLE
Just a general writeup of observations after using Streamly

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#504]
Hello everyone,

I've decided to experiment with Streamly in context of [this](https://github.com/mryndzionek/composable-sdr) project. One missing piece that I needed was something that offers 'distribution' like `Folds`, but is expressive enough to handle resource management. I've come up with [this](https://github.com/mryndzionek/composable-sdr/blob/master/src/ComposableSDR.chs#L95) type called `Pipe` (for lack of a better name...). `Pipes` are an instance of `Category`, so compose nicely with each other and `Folds` can be 'decorated' with `Pipes` using [addPipe](https://github.com/mryndzionek/composable-sdr/blob/master/src/ComposableSDR.chs#L512). Additionally `Pipes` can be composed using [this](https://github.com/mryndzionek/composable-sdr/blob/master/src/ComposableSDR.chs#L1076) operator that connects multiple pipes parallely and that I couldn't write for `Folds` directly. 

And now, I know that there are plans to extend expressivity of `Folds` and I think that it would be great to have them re-designed so, that both described use cases (resource management + parallel multiplexing) are possible.

**Comment by harendra-kumar** [comment]
Thanks for sharing this @mryndzionek . Your SDR project looks pretty cool. I used to be a radio enthusiast long time ago.

I see you are using several Internal modules from Streamly. We will try to expose those via regular modules and make them officially supported functions wherever it makes sense so that you do not need to rely on Internal modules because Internal modules can change without notice. I will take a look at the `Pipe` type and see how we can have equivalent functionality available from Streamly.

**Comment by mryndzionek** [comment]
Thank **you** @harendra-kumar for Streamly. I wish there were more people who do not settle on status quo. People who see better ways of doing things and who can act on this vision and on top
of that are willing to share their work with others.

I will try to contribute to Streamly as much as can. Relying on internal modules in not a big problem for now, as I'm still experimenting, but having some of the facilities in external API would definitely be nice.

Thanks again!
