### ISSUE TITLE
Module conventions

### ISSUE THREAD

**Issue by shlok** [composewell/streamly#544]
For 3rd party Streamly-related packages, do you have any thoughts on, e.g., `Streamly.External.LMDB` versus simply `Streamly.LMDB`?

I see both forms being used out there; e.g., [`Streamly.Csv`](https://hackage.haskell.org/package/streamly-cassava) and [`Streamly.External.Posix.DirStream`](https://hackage.haskell.org/package/streamly-posix), and I wonder if you have any preferences about it.

**Comment by harendra-kumar** [comment]
We had discussed this at some point in the past. Both these options were reasonable. We decided to use Streamly.*` for modules that are meant to be native to streamly and `Streamly.External.*` for interoperability modules to existing packages (e.g. Streamly.External.ByteString) so that there is no conflict if such a name is to be used in streamly natively. However, this is just a rough guideline.

Is this supposed to be shim to work with an existing lmdb package or a native module?

**Comment by shlok** [comment]
Thanks, @harendra-kumar. This is as expected and reasonable. I will use `Streamly.External.LMDB`, allowing for a native `Streamly.LMDB` in the future.

My package will not work with any existing LMDB Haskell package. It will however call C functions from `lmdb.h` (in a similar way that the existing (and apparently abandoned) [lmdb](https://hackage.haskell.org/package/lmdb) package does it).
