### ISSUE TITLE
Benchmarks take an awful long time to build from scratch.

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#647]
- Try to reduce the number of dependencies.

**Comment by harendra-kumar** [comment]
It may not be a "good first issue" unless you describe how to reduce the dependencies.

I think you are talking about the case when the "chart" executable is built, and the chart executable has a lot of dependencies due to `bench-show`. In that case its more about reducing the dependencies of `bench-show`.

See #598 . If we can use the bench-show executable directly then it will not remain a dependency of streamly.

**Comment by harendra-kumar** [comment]
Closing this, it should be pursued as #598, if at all.
