### ISSUE TITLE
Question about consuming infinite monadic streams

### ISSUE THREAD

**Issue by zoran119** [composewell/streamly#77]
Given a function `getInfiniteStream` which produces an infinite list of monadic actions (say HTTP calls), I'm trying to consume first `n` elements of this list like this:

`S.take 10 $ (asyncly getInfiniteStream)`

I was hoping that the producer would only create 10 items in the stream because that's all the consumer needs, but what I'm seeing is that many items are produced and first 10 that come back are consumed by the consumer (ie. many more than 10 HTTP calls are made).

My end goal is this concept of an infinite stream that can be consumed with `S.take`, `S.takeWhile`, `S.filter`... and combinations of those, but the underlying stream to be produced non-serially.

Is there a way to do this with Streamly?

**Comment by harendra-kumar** [comment]
> I was hoping that the producer would only create 10 items

For that to happen we will need to pass a hint from `take` to the concurrent scheduler or to specify the max concurrency limit using another combinator, this is in the plan but not implemented yet.

I guess you want the infinite stream generation to be serial but the ability to consume it in parallel with the generation of the stream. Let me know if my understanding it correct. There are multiple ways to achieve that, some of the ways that I can think of - on the master branch in this repo i.e. in the unreleased version:

1) use `asyncly . replicateM 10` to generate the stream. It will perform all 10 requests concurrently but no more.
2) use `asyncly . unfoldrM` to generate the stream, it will do the processing in parallel with serial generation.
3) use concurrent application operator i.e. `take 10 |$ (serially  getInfiniteStream)` it will do the processing in parallel with serial generation.

You can build and view the haddock for the head version in this repo to see the docs.

**Comment by harendra-kumar** [comment]
@zoran119 the behavior of `take` that you were looking for has been released in streamly 0.4.0 on hackage. `take` will now limit concurrency of the enclosed stream. However, note that it is not theoretically possible to limit the concurrency of `takeWhile` and `filter` etc in the same way, because to be able to decide what to filter you need to generate it first.

The same behavior as `take` is possible for `head` and `null` combinators which is not implemented in 0.4.0 but will get implemented in the next release.

Let me know your feedback or any suggestions in case you happen to give it a try.

**Comment by harendra-kumar** [comment]
Note that this applies only to bounded concurrency streams which excludes `Parallel` stream because it provides unbounded and unlimited concurrency. For example, you may want to run `n` actions in parallel and take the one that finishes first, in such cases you can use `take` with a `Parallel` stream and it will run all actions concurrently.

**Comment by zoran119** [comment]
Thank you very much @harendra-kumar, I will have a look at 0.4.0 and let you know how I go. I really appreciate your response.
