### ISSUE TITLE
RFC - Module organization

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#8]
Currently we have Streamly as the top level module. I am considering moving it to `Data.Streamly` to be consistent with other such libraries e.g. `Data.List`, `Data.Machines`, `Data.Conduit`. On the other hand, libraries like `Streaming` and `Pipes` use a top level name convention and Streamly currently follows that. However, the former seems more prevalent and perhaps a little bit more organized. 

Any comments/feedback on this is welcome.

**Comment by harendra-kumar** [comment]
Also, instead of `Prelude` maybe have a `Data.Stream` module which is sort of a parallel to `Data.List`.

**Comment by sjakobi** [comment]
I think you should stick with the existing `Streamly` name, mostly because it's less typing than `Data.Streamly`.

Also, `Data.Streamly` doesn't really offer any additional info on what the module is about.

Regarding `Streamly.Prelude` vs. `Data.Stream`, I again prefer the existing name. `Data.Stream` doesn't reveal which package the module comes from.

**Comment by harendra-kumar** [comment]
Thanks for the feedback Simon. This looks like less work for me, absolutely nil :-) Unless someone else comes and provide arguments to the contrary.
