### ISSUE TITLE
logict example ?

### ISSUE THREAD

**Issue by pcarbonn** [composewell/streamly#81]
The first page of Streamly's documentation says "streamly subsumes the functionality of (..) the logic programming library logict."  It's not clear how.  Could you provide some hints ?  Could you add an example the example directory ?

**Comment by harendra-kumar** [comment]
Its true, it may not be obvious. The main idea is that logict is a list transformer and so is streamly. Everything that you can do with logict can be done with streamly, here is how they map one to one:

1) The `Monad` instance of `LogicT` is the same as the Monad of `streamly` (both are list transformers)
2) `Alternative` and `MonadPlus` of `LogicT` are the same as the `Monoid` of `streamly`, they all append.
3) LogicT.observeT = Streamly.head
4) LogicT.observeManyT n = Streamly.toList . Streamly.take n 
5) LogicT.observeAllT = Streamly.toList 
6) `MonadLogic.msplit` = `Streamly.uncons`

The `MonadLogic` instance can be defined just by defining `msplit` as `uncons` as listed above. But you do not need to do that because all the functionality of MonadLogic class is already available in some convenient form in streamly. Since we have the equivalent of `msplit` we can provably express everything that MonadLogic can.

1) `MonadLogic.msplit` = `Streamly.uncons`, also `MonadLogic.reflect` = `Streamly.cons`
2) `MonadLogic.interleave` is the same as the Semigroup/Monoid of `WSerial` type in streamly
3) `MonadLogic.>>-` is the same is the Monad bind of `WSerial`
4) `MonadLogic.once` = `Streamly.take 1`
5) `ifte` and `lnot` can be easily expressed in terms of `cons` and `uncons`.

Streamly is better than logict in many respects:

1. `logict` shows O(n^2) complexity with `observeManyT`, it is not even usable if you want to extract something like 1000 results or more. Streamly has linear complexity, you can easily extract a million results without any problem.
2. streamly is equal or faster than logict in all other operations.
3. logict is serial, streamly is concurrent so you can do scalable, concurrent logic programming.

Let me know if you have any questions. To have a trivial usage examples of all list-transformer packages including streamly, logict and pipes in a benchmark package. I can upload that on github if that can help.

**Comment by pcarbonn** [comment]
Thank you for your response, this is very helpful. Streamly does seem better indeed.

I'm working on a Prolog-like solver, with unification-fd, so if you have any example in that direction, it would be very useful.

**Comment by harendra-kumar** [comment]
If you can point me to an example(s) of your choice using logic-t/unification-fd I can try converting it to streamly.

**Comment by pcarbonn** [comment]
The [ds-kanren](http://hackage.haskell.org/package/ds-kanren) package is the closest thing I could find: it uses logict (but has its own unification, instead of using unification-fd).

**Comment by pcarbonn** [comment]
Also, this sentence does not make sense to me: 

> `Alternative` and `MonadPlus` of `LogicT` are the same as the `Monoid` of `streamly,` they all append.  

It seems to imply that `Alternative` and `MonadPlus` are the same as `Monoid`, which is a stretch.

**Comment by harendra-kumar** [comment]
Here is a version of the package https://github.com/composewell/ds-kanren using streamly.

**Comment by harendra-kumar** [comment]
> It seems to imply that Alternative and MonadPlus are the same as Monoid, which is a stretch.

It depends on what implementation you choose for the instances. `logict` has chosen `Alternative` for appends, `streamly` have chosen `Monoid` for that. But the functionality is equivalent. However, this does not mean that `Alternative` as a concept is the same as `Monoid` as a concept.

Either one may make sense depending on how you think about it. If you think of it as appends then it looks like `Monoid`. If you think of it as different choices that you want to choose from using non-determinism then `Alternative` makes sense too.

**Comment by pcarbonn** [comment]
Excellent: thank you for the ds-kanren package.

I can see the similarity of `Alternative` and `Monoid`, but `guard` is in one, and not in the other.  I wonder how you implement it in a Monoid ?  Using a filter ?

**Comment by harendra-kumar** [comment]
Just use `nil` or `mempty` in place of `empty`.

```haskell
guard True      =  pure ()
guard False     =  nil
```

For example, [see this function](https://github.com/composewell/streamly/blob/f1f322cb2cd59199ec4435018a3547fdd45bddfa/benchmark/NestedOps.hs#L94). It uses something similar to `guard`.

**Comment by pcarbonn** [comment]
OK. Thanks.  I'll look into it.  One day I'll be a Haskell hero... :-)

**Comment by harendra-kumar** [comment]
It will be useful to have the info in this issue to be documented in the tutorial.

**Comment by pcarbonn** [comment]
It would also be useful to add a comparison with logict in a benchmark.

**Comment by flip111** [comment]
@pcarbonn are you going to publish your solver ?

**Comment by pcarbonn** [comment]
This project has been postponed. Thanks for the interest.

**Comment by pranaysashank** [comment]
Closing this issue. Feel free to reopen if needed.
