### ISSUE TITLE
provide means of returning accumulated bytes from Parser

### ISSUE THREAD

**Issue by agentm** [composewell/streamly#861]
We are [parsing length-prefixed bytes](https://github.com/agentm/curryer/blob/28ff1d031078af4a17fa326d43340474571df0c3/src/Network/RPC/Curryer/Server.hs#L168) from a socket to be deserialized by a separate package like this:

```haskell
	c <- fromIntegral <$> word32P
        --streamly can't handle takeEQ 0, so add special handling                             
	if c == 0 then
          pure BS.empty
          else
          BS.pack <$> P.takeEQ c s
```
This is fine for small messages, but the overhead of converting from Array to [Word] to ByteString pops up in profiling for larger messages. 

Is there an API which can provide the underlying accumulated buffer with minimal overhead as Array or ByteString directly?

**Comment by adithyaov** [comment]
> --streamly can't handle takeEQ 0, so add special handling  

This has been fixed in master and the fix will be available in 0.8.0

> Is there an API which can provide the underlying accumulated buffer with minimal overhead as Array or ByteString directly?

This https://hackage.haskell.org/package/streamly-bytestring is what you're looking for.

**Comment by adithyaov** [comment]
> --streamly can't handle takeEQ 0, so add special handling

In the master branch, `takeEQ 0` works as expected but requires scrutinizing an additional input. If this behavior does not affect your use-case you can use `takeEQ` from `master`.

There are plans to fix this in the near future, See: https://github.com/composewell/streamly/issues/671

**Comment by harendra-kumar** [comment]
Do not use lists as your intermediate type, that's very inefficient. Instead of:

```
          BS.pack <$> P.takeEQ c s
```

Use:

```
          BS.pack <$> P.takeEQ c (A.writeN c)
```

If you have to you can convert the array to bytestring using the streamly-bytstring package, the conversion is free.

You can find similar parsing code [here](https://github.com/composewell/streamly/blob/c671f2e850791e911a6bc4a494ab7f28948243de/src/Streamly/Internal/FileSystem/Event/Linux.hs#L773).

1. You should use streamly arrays wherever you need bytestring. bytestring is not required if you are using streamly unless you are interfacing with something that requires bytestring. In case you need to interconvert between arrays and bytestrings use streamly-bytestring package.
2. For deserializing common data types see https://composewell.github.io/streamly/master/Streamly-Internal-Data-Binary-Decode.html

**Comment by agentm** [comment]
Thanks for the detailed response. With your suggested changes in place, we gain over a 100% performance improvement for large messages!
