### ISSUE TITLE
Run benchmarks in quick mode in one of the CIs

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#952]
--quick mode runs them fast, so should not be very expensive. We can add this in the fusion-plugin CI.

**Comment by yaitskov** [comment]
Hi, thanks for  the [conference talk](https://youtu.be/aJvwORrBJ0o).
I am looking for an example of benchmark report integrated into CI and I was able to find such info on streamly PR pages, because the project pays so much attention to performance. Could you confirm that there is no such info generated per push to GIT branch?

**Comment by harendra-kumar** [comment]
We are working on it. See #1423 . A full report would be too much data to look at because we have a very large number of benchmarks, we will only be generating the benchmarks that regressed or improved in a PR.

**Comment by harendra-kumar** [comment]
Closing this, it will be fixed by #1433 .
